export interface CriteriaOption {
  value: string
  label: string
  description: string
}

/**
 * Every `is:` keyword Scryfall's own Advanced Search "Criteria" field
 * offers, extracted from scryfall.com/advanced (109 total after removing
 * one duplicate — "Universes Beyond" and "Universesbeyond" both mapped to
 * the same `is:universesbeyond` value). Spot-checked against
 * api.scryfall.com/cards/search across the list. Not documented in the
 * plain-text syntax reference (scryfall.com/docs/syntax) — this picker is
 * the only place that lists them out.
 */
export const CRITERIA_OPTIONS: CriteriaOption[] = [
  { value: 'adventure', label: 'Adventure', description: 'the cards use the Adventure layout' },
  { value: 'arenaid', label: 'Arena ID', description: 'the cards have an Arena ID' },
  { value: 'artseries', label: 'Art Series', description: 'the cards are Art Series' },
  { value: 'artist', label: 'Artist', description: 'have artists' },
  { value: 'artistmisprint', label: 'Artist Misprint', description: 'cards with a misprinted artist' },
  { value: 'lights', label: 'Attraction Lights', description: 'the cards have attraction lights' },
  { value: 'atypical', label: 'Atypical', description: "the cards aren't printed with standard frames and effects" },
  { value: 'augmentation', label: 'Augment', description: 'the cards are augment pieces' },
  { value: 'back', label: 'Back', description: 'the cards have non-standard backs' },
  { value: 'bear', label: 'Bear', description: 'the cards are 2/2/2 bears' },
  { value: 'beginnerbox', label: 'Beginner Box', description: 'part of a Beginner Box' },
  { value: 'booster', label: 'Booster', description: 'cards that are included in the standard contents of draft boosters' },
  { value: 'borderless', label: 'Borderless', description: 'the cards are borderless' },
  { value: 'brawlcommander', label: 'Brawl Commander', description: 'the cards can be your Brawl commander' },
  { value: 'buyabox', label: 'Buy-a-Box', description: 'Buy-a-Box promos' },
  { value: 'cardmarket', label: 'Cardmarket ID', description: 'the cards have a Cardmarket ID' },
  { value: 'class', label: 'Class Layout', description: 'the cards are Class-type' },
  { value: 'ci', label: 'Color Indicator', description: 'the cards have color indicators' },
  { value: 'colorshifted', label: 'Colorshifted', description: 'the cards have a colorshifted frame' },
  { value: 'commander', label: 'Commander', description: 'the cards can be your commander' },
  { value: 'companion', label: 'Companion', description: 'the cards are Companions' },
  { value: 'contentwarning', label: 'Content Warning', description: 'the cards have content warnings' },
  { value: 'covered', label: 'Covered', description: 'the cards are covered' },
  { value: 'manland', label: 'Creature Land', description: 'the cards are lands that become creatures' },
  { value: 'datestamped', label: 'Datestamped', description: 'cards with a date stamp' },
  { value: 'default', label: 'Default', description: 'the cards are printed with standard frames and effects' },
  { value: 'digital', label: 'Digital', description: 'the cards are digital prints' },
  { value: 'doublesided', label: 'Double Sided', description: 'the cards are double-sided' },
  { value: 'duelcommander', label: 'Duel Commander', description: 'the cards can be your Duel Commander' },
  { value: 'etb', label: 'E T B', description: 'the cards have an ETB effect' },
  { value: 'englishart', label: 'English Art', description: 'the cards have art that has been printed in English' },
  { value: 'etch', label: 'Etched', description: 'the cards are available in etched foil' },
  { value: 'extended', label: 'Extended Art', description: 'the cards are extended art frames' },
  { value: 'extra', label: 'Extra', description: 'the cards are Scryfall "extras"' },
  { value: 'ff', label: 'Final Fantasy', description: 'from Final Fantasy' },
  { value: 'firstprint', label: 'First Printing', description: 'the card is the first printing' },
  { value: 'flavorname', label: 'Flavor Name', description: 'the cards have flavor names' },
  { value: 'flavor', label: 'Flavor Text', description: 'the cards have flavor text' },
  { value: 'flip', label: 'Flip', description: 'the cards flip' },
  { value: 'foil', label: 'Foil', description: 'the cards are available in foil' },
  { value: 'fbb', label: 'Foreign Black Border', description: 'Cards printed in black border in non-English editions of white-border sets' },
  { value: 'fwb', label: 'Foreign White Border', description: 'the cards are "foreign white border" prints' },
  { value: 'frenchvanilla', label: 'French Vanilla', description: 'the cards are French vanilla' },
  { value: 'fullart', label: 'Full Art', description: 'cards with full extended art' },
  { value: 'funny', label: 'Funny', description: 'the cards are funny' },
  { value: 'future', label: 'Future', description: 'the cards have the future frame' },
  { value: 'gamechanger', label: 'Game Changer', description: 'on the Commander Game Changer list' },
  { value: 'gameday', label: 'Game Day', description: 'Game Day promos' },
  { value: 'hires', label: 'Highres', description: 'the cards have hi-res scans' },
  { value: 'historic', label: 'Historic', description: 'the cards are historic' },
  { value: 'splitmana', label: 'Hybrid Mana', description: 'the cards have hybrid mana' },
  { value: 'illustration', label: 'Illustration', description: 'have illustration IDs' },
  { value: 'intropack', label: 'Intro Pack', description: 'exclusive Intro Pack cards' },
  { value: 'invitational', label: 'Invitational Card', description: 'Invitational cards' },
  { value: 'leveler', label: 'Leveler', description: 'the cards have Level Up' },
  { value: 'localizedname', label: 'Localized Name', description: 'the cards have localized names' },
  { value: 'mtgoid', label: 'MTGO ID', description: 'the cards have a MTGO ID (CatID)' },
  { value: 'masterpiece', label: 'Masterpiece', description: 'the cards are masterpieces' },
  { value: 'meld', label: 'Meld', description: 'the cards meld' },
  { value: 'modal', label: 'Modal', description: 'the cards have modal effects' },
  { value: 'mdfc', label: 'Modal Double Faced', description: 'the cards are modal DFCs' },
  { value: 'modern', label: 'Modern', description: 'the cards have the 2003 frame' },
  { value: 'multiverse', label: 'Multiverse ID', description: 'the cards have a Multiverse ID' },
  { value: 'new', label: 'New', description: 'the cards have a new frame' },
  { value: 'nonfoil', label: 'Nonfoil', description: 'the cards are available in nonfoil' },
  { value: 'notuniversesbeyond', label: 'Notuniversesbeyond', description: 'Printings not from Universes Beyond products' },
  { value: 'oathbreaker', label: 'Oathbreaker', description: 'the cards can be your oathbreaker' },
  { value: 'old', label: 'Old', description: "the cards have the '93/97 frame" },
  { value: 'outlaw', label: 'Outlaw', description: 'the cards are Assassins, Mercenaries, Pirates, Rogues, or Warlocks' },
  { value: 'oversized', label: 'Oversized', description: 'larger than standard card size' },
  { value: 'partner', label: 'Paired Commander', description: 'the cards have multi-commander mechanics' },
  { value: 'paperart', label: 'Paper Art', description: 'the cards have art that has been printed in paper' },
  { value: 'party', label: 'Party', description: 'the cards are Clerics, Rogues, Warriors, or Wizards' },
  { value: 'permanent', label: 'Permanent', description: 'the cards become permanents' },
  { value: 'phyrexia', label: 'Phyrexian Mana', description: 'the cards have Phyrexian mana' },
  { value: 'planar', label: 'Planar', description: 'the cards are planar deck cards' },
  { value: 'planeswalkerdeck', label: 'Planeswalker Deck', description: 'exclusive Planeswalker Deck cards' },
  { value: 'prepare', label: 'Prepare', description: 'the cards have prepared spell parts' },
  { value: 'prerelease', label: 'Prerelease Promo', description: 'set prerelease event promos' },
  { value: 'printedtext', label: 'Printed Text', description: 'the cards have their printed text listed' },
  { value: 'promo', label: 'Promo', description: 'the cards are promotional prints' },
  { value: 'related', label: 'Related', description: 'the cards have related cards' },
  { value: 'release', label: 'Release Promo', description: 'set release event promos' },
  { value: 'reprint', label: 'Reprint', description: 'the cards are reprints' },
  { value: 'reserved', label: 'Reserved List', description: 'on the Reserved List' },
  { value: 'resource', label: 'Resource ID', description: 'the cards have a Resource ID' },
  { value: 'reversible', label: 'Reversible', description: 'the cards are reversible cards' },
  { value: 'stamp', label: 'Security Stamp', description: 'the cards have a security stamp' },
  { value: 'showcase', label: 'Showcase', description: 'the cards are showcases' },
  { value: 'spell', label: 'Spell', description: 'the cards are spells' },
  { value: 'spellbook', label: 'Spellbook', description: 'the cards have spellbooks' },
  { value: 'spikey', label: 'Spikey', description: 'cards that have ever been banned or restricted' },
  { value: 'split', label: 'Split Card', description: 'the cards are split' },
  { value: 'stamped', label: 'Stamped', description: 'cards with a non-date stamp' },
  { value: 'startercollection', label: 'Starter Collection', description: 'part of a Starter Collection' },
  { value: 'starterdeck', label: 'Starter Deck', description: 'exclusive to a Starter deck' },
  { value: 'story', label: 'Story Spotlight', description: 'the cards are Story Spotlights' },
  { value: 'tcgplayer', label: 'TCGplayer ID', description: 'the cards have a TCGplayer ID' },
  { value: 'textless', label: 'Textless', description: 'printed without rules text' },
  { value: 'token', label: 'Token', description: 'the cards are tokens' },
  { value: 'tombstone', label: 'Tombstone', description: 'the cards have the Odyssey tombstone mark' },
  { value: 'transform', label: 'Transform', description: 'the cards transform' },
  { value: 'translucent', label: 'Transluscent', description: 'cards with a translucent card frame' },
  { value: 'onlyprint', label: 'Unique', description: 'the card has been printed exactly once' },
  { value: 'universesbeyond', label: 'Universes Beyond', description: 'from a Universes Beyond edition' },
  { value: 'vanilla', label: 'Vanilla', description: 'the cards are vanilla' },
  { value: 'variation', label: 'Variation', description: 'the cards are variations of standard printings' },
  { value: 'watermark', label: 'Watermark', description: 'the cards have watermarks' },
  { value: 'worthy', label: 'Worthy', description: 'the creatures are considered worthy' },
]
